### ISSUE TITLE
Create Page, Set, and Activity APIs

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/portal#7] opened 2020-06-03 01:33 UTC
Create APIs that give a list of pages, a list of Sets for a given page, and a detail endpoint that returns all needed data for the Activity Detail Page

The detail endpoint should have all properties for both zoom and youtube live scenarios.

**Comment by danielabreo** [comment] 2020-06-29 04:01
duplicate of #17 #18 and #19

**Closed** 2020-06-29 04:01 UTC
